tbx/urls.py
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import never_cache
from django.views.decorators.vary import vary_on_headers

from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.models import Page
from wagtail.utils.urlpatterns import decorate_urlpatterns

from tbx.core import urls as torchbox_urls
from tbx.core.utils.cache import (
    get_default_cache_control_decorator,
    get_default_cache_control_method_decorator,
)
from tbx.core.utils.views import page_not_found, server_error
from tbx.core.views import robots, switch_mode


private_urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("switch-mode/", switch_mode, name="switch_mode"),
] + decorate_urlpatterns([path("documents/", include(wagtaildocs_urls))], never_cache)

urlpatterns = [
    path("sitemap.xml", sitemap),
    path("robots.txt", robots),
]


if settings.DEBUG or settings.TEST:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Add views for testing 404 and 500 templates
    private_urlpatterns += [
        # Add views for testing 404 and 500 templates
        path("test404/", page_not_found),
        path("test500/", server_error),
    ]

    # Django Debug Toolbar
    if apps.is_installed("debug_toolbar"):
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


urlpatterns += [
    path("", include(torchbox_urls)),
]

# Style guide
if getattr(settings, "PATTERN_LIBRARY_ENABLED", False) and apps.is_installed(
    "pattern_library"
):
    from tbx.project_styleguide.views import example_form

    private_urlpatterns += [
        path("pattern-library/example-form/", example_form),
        path("pattern-library/", include("pattern_library.urls")),
    ]


# Set public URLs to use public cache.
urlpatterns = decorate_urlpatterns(urlpatterns, get_default_cache_control_decorator())

# Set vary header to instruct cache to serve different version on different
# cookies, different request method (e.g. AJAX) and different protocol
# (http vs https).
urlpatterns = decorate_urlpatterns(
    urlpatterns,
    vary_on_headers(
        "Cookie", "X-Requested-With", "X-Forwarded-Proto", "Accept-Encoding"
    ),
)

Page.serve = get_default_cache_control_method_decorator(Page.serve)

# Join private and public URLs.
urlpatterns = (
    private_urlpatterns
    + urlpatterns
    + [
        # Add Wagtail URLs at the end.
        # Wagtail cache-control is set on the page models's serve methods.
        path("", include(wagtail_urls))
    ]
)

# Error handlers
handler404 = page_not_found
handler500 = server_error

tbx/work/models.py
from itertools import chain
import math
import string

from django import forms
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models
from django.db.models import Case, DateField, F, Q, When
from django.dispatch import receiver
from django.utils.functional import cached_property
from django.utils.http import urlencode

from modelcluster.fields import ParentalManyToManyField
from wagtail.admin.panels import FieldPanel, InlinePanel, MultiFieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page
from wagtail.signals import page_published

from bs4 import BeautifulSoup

from tbx.core.blocks import StoryBlock
from tbx.core.models import BasePage
from tbx.core.utils.fields import StreamField
from tbx.core.utils.models import (
    ColourThemeMixin,
    ContactMixin,
    NavigationFields,
    SocialFields,
)
from tbx.images.models import CustomImage
from tbx.taxonomy.models import Sector, Service
from tbx.work.blocks import WorkStoryBlock


class HistoricalWorkPage(BasePage):
    """
    This represents Work Pages as they were prior to the 2024
    rebuild of the site. It is kept here to display the older
    work pages that were created prior to 2024.
    """

    template = "patterns/pages/work/historical_work_page.html"

    # Prevent this page type from being created in Wagtail Admin
    is_creatable = False
    parent_page_types = ["WorkIndexPage"]

    date = models.DateField("Post date", blank=True, null=True)
    body = StreamField(StoryBlock())
    body_word_count = models.PositiveIntegerField(null=True, editable=False)
    visit_the_site = models.URLField(blank=True)

    # Renamed from feed_image to allow prefetch of field common to WorkPage and
    # HistoricalWorkPage
    header_image = models.ForeignKey(
        "images.CustomImage",
        help_text="Image used on listings and social media.",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        verbose_name="Feed image",
    )
    listing_summary = models.CharField(max_length=255, blank=True)
    related_sectors = ParentalManyToManyField(
        "taxonomy.Sector",
        related_name="historical_case_studies",
        blank=True,
    )
    related_services = ParentalManyToManyField(
        "taxonomy.Service", related_name="historical_case_studies"
    )
    client = models.TextField(blank=True)

    # We are setting `db_index=False` on the social_image, otherwise
    # we encounter migration errors on the New Work Page.
    # See Django bug: <https://code.djangoproject.com/ticket/23577>
    social_image = models.ForeignKey(
        "images.CustomImage",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        db_index=False,
    )

    def set_body_word_count(self):
        body_basic_html = self.body.stream_block.render_basic(self.body)
        body_text = BeautifulSoup(body_basic_html, "html.parser").get_text()
        remove_chars = string.punctuation + "“”’"
        body_words = body_text.translate(
            body_text.maketrans(dict.fromkeys(remove_chars))
        ).split()
        self.body_word_count = len(body_words)

    @cached_property
    def work_index(self):
        ancestor = WorkIndexPage.objects.ancestor_of(self).order_by("-depth").first()

        if ancestor:
            return ancestor
        else:
            # No ancestors are work indexes,
            # just return first work index in database
            return WorkIndexPage.objects.live().public().first()

    @property
    def first_author(self):
        """Safely return the first author if one exists."""
        author = self.authors.first()
        if author:
            return author.author
        return None

    @cached_property
    def related_works(self):
        services = self.related_services.all()
        sectors = self.related_sectors.all()
        # get 4 pages with same services and exclude self page
        works = (
            HistoricalWorkPage.objects.filter(
                Q(related_sectors__in=sectors) | Q(related_services__in=services)
            )
            .live()
            .public()
            .distinct()
            .order_by(F("date").desc(nulls_last=True))
            .exclude(pk=self.pk)[:4]
        )
        return works

    @cached_property
    def sectors(self):
        return self.related_sectors.all()

    @cached_property
    def services(self):
        return self.related_services.all()

    @property
    def tags(self):
        return chain(self.services, self.sectors)

    @property
    def read_time(self):
        if self.body_word_count:
            return math.ceil(self.body_word_count / 275)
        else:
            return "x"

    @property
    def listing_image(self):
        return self.header_image

    @property
    def type(self):
        return "CASE STUDY"

    content_panels = BasePage.content_panels + [
        FieldPanel("client", classname="client"),
        InlinePanel("authors", label="Author", min_num=1),
        FieldPanel("date"),
        FieldPanel("body"),
        FieldPanel("visit_the_site"),
    ]

    promote_panels = (
        [
            MultiFieldPanel(Page.promote_panels, "Common page configuration"),
        ]
        + NavigationFields.promote_panels
        + ColourThemeMixin.promote_panels
        + ContactMixin.promote_panels
        + [
            FieldPanel("header_image"),
            FieldPanel("listing_summary"),
            FieldPanel("related_sectors", widget=forms.CheckboxSelectMultiple),
            FieldPanel("related_services", widget=forms.CheckboxSelectMultiple),
            MultiFieldPanel(SocialFields.promote_panels, "Social fields"),
        ]
    )


class WorkPage(BasePage):
    template = "patterns/pages/work/work_page.html"
    parent_page_types = ["WorkIndexPage"]

    intro = RichTextField(blank=True)
    logo = models.ForeignKey(
        "images.CustomImage",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    client = models.CharField(max_length=255)
    date = models.DateField("post date", blank=True, null=True)
    body_word_count = models.PositiveIntegerField(null=True, editable=False)

    header_image = models.ForeignKey(
        "images.CustomImage",
        verbose_name="Image",
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    header_image_is_decorative = models.BooleanField(
        help_text="If checked, this will make the alt text empty.",
        default=False,
    )
    header_alt_text = models.CharField(
        blank=True,
        max_length=255,
        help_text="By default the image title (shown above) is used as the alt text. "
        "Use this field to provide more specific alt text if required.",
    )

    header_caption = models.CharField("caption", max_length=255, blank=True)
    header_attribution = models.CharField("attribution", max_length=255, blank=True)

    body = StreamField(WorkStoryBlock())

    listing_summary = models.CharField(max_length=255, blank=True)
    related_services = ParentalManyToManyField(
        "taxonomy.Service", related_name="case_studies"
    )
    related_sectors = ParentalManyToManyField(
        "taxonomy.Sector",
        related_name="case_studies",
        blank=True,
    )

    content_panels = BasePage.content_panels + [
        FieldPanel("intro"),
        InlinePanel("authors", label="Author", min_num=1),
        FieldPanel("logo"),
        FieldPanel("client", classname="client"),
        FieldPanel("date"),
        MultiFieldPanel(
            [
                FieldPanel("header_image"),
                FieldPanel("header_alt_text"),
                FieldPanel("header_image_is_decorative"),
                FieldPanel("header_caption"),
                FieldPanel("header_attribution"),
            ],
            heading="Header image",
        ),
        FieldPanel("body"),
    ]

    promote_panels = (
        [
            MultiFieldPanel(Page.promote_panels, "Common page configuration"),
        ]
        + NavigationFields.promote_panels
        + ColourThemeMixin.promote_panels
        + ContactMixin.promote_panels
        + [
            FieldPanel("listing_summary"),
            MultiFieldPanel(
                [
                    FieldPanel("related_sectors", widget=forms.CheckboxSelectMultiple),
                    FieldPanel("related_services", widget=forms.CheckboxSelectMultiple),
                ],
                heading="Taxonomies",
            ),
            MultiFieldPanel(SocialFields.promote_panels, "Social fields"),
        ]
    )

    @property
    def type(self):
        return "CASE STUDY"

    @cached_property
    def sectors(self):
        return self.related_sectors.all()

    @cached_property
    def services(self):
        return self.related_services.all()

    @property
    def tags(self):
        return chain(self.services, self.sectors)

    @cached_property
    def first_author(self):
        """Safely return the first author if one exists."""
        if author := self.authors.first():
            return author.author
        return None

    @cached_property
    def header_image_alt_text(self):
        if header_alt_text := self.header_alt_text:
            return header_alt_text
        return self.header_image.title

    def get_related_works(self):
        prefetch_listing_images = models.Prefetch(
            "header_image",
            queryset=CustomImage.objects.prefetch_renditions(
                "fill-370x370|format-webp",
                "fill-370x335|format-webp",
                "fill-740x740|format-webp",
                "fill-740x670|format-webp",
            ),
        )

        return (
            # Assumption that work pages for the same division
            # will be under the same work index page.
            WorkPage.objects.sibling_of(self)
            .live()

tbx/project_styleguide/forms.py
from django import forms


class ExampleForm(forms.Form):
    """Demonstration of all common Django form fields / widgets"""

    single_line_text = forms.CharField(
        max_length=255, help_text="This is some help text"
    )
    single_line_text_optional = forms.CharField(required=False)
    single_line_text_disabled = forms.CharField(disabled=True)
    multi_line_text = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 10, "cols": 40})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"autocomplete": "email", "autocapitalize": "off"}
        )
    )
    number = forms.IntegerField(widget=forms.NumberInput(attrs={"step": 1}))
    url = forms.URLField(label="URL")
    date = forms.DateField(widget=forms.DateInput(attrs={"placeholder": "DD/MM/YYYY"}))
    datetime = forms.DateTimeField()
    file = forms.FileField(help_text="Please upload a CSV or XLS")
    password = forms.CharField(widget=forms.PasswordInput())
    hidden = forms.CharField(widget=forms.HiddenInput())
    single_checkbox = forms.BooleanField()
    choices = (("one", "One"), ("two", "Two"), ("three", "Three"), ("four", "Four"))
    multiple_checkboxes = forms.MultipleChoiceField(
        choices=choices, widget=forms.CheckboxSelectMultiple()
    )
    select = forms.ChoiceField(choices=choices)
    select_multiple = forms.MultipleChoiceField(choices=choices)
    radio_buttons = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())

tbx/project_styleguide/views.py
from django.shortcuts import render

from .forms import ExampleForm


def example_form(request):
    if request.method == "POST":
        form = ExampleForm(request.POST)
        form.add_error(None, "An example non-field error.")
    else:
        form = ExampleForm()

    return render(
        request, "patterns/_pattern_library_only/example_form.html", {"form": form}
    )

tbx/project_styleguide/templates/patterns/organisms/header/header.html
{% load wagtailcore_tags wagtail_cache navigation_tags %}
{% wagtail_site as current_site %}
<header class="header">
    {% include "patterns/atoms/skip-link/skip-link.html" %}
    <div class="header__top">
        <div class="grid">
            <div class="grid__header-nav">
            {# Primary desktop navigation #}
                <nav aria-label="Main navigation" class="primary-nav-desktop">
                    {% wagtailcache 600 "primarynav" current_site.pk is_pattern_library %}
                        <ul class="primary-nav-desktop__list">
                            <li class="primary-nav-desktop__item">
                                <a href="/" aria-label="Homepage link" class="primary-nav-desktop__link">
                                    <span class="primary-nav-desktop__text">Home</span>
                                </a>
                            </li>
                            {% primarynav %}
                        </ul>
                    {% endwagtailcache %}
                </nav>

                {# Primary mobile menu toggle #}
                {% get_top_level_parent_page as parent_page %} {# Get the top-level parent page #}
                {% firstof parent_page.title "Home" as parent_title %} {# Get the parent's title, or Home if no parent #}
                <button
                    aria-expanded="false"
                    aria-haspopup="true"
                    aria-label="Mobile menu toggle - currently viewing '{{ parent_title }}' or pages below it"
                    class="header__primary-menu-toggle"
                    data-primary-mobile-menu-toggle
                >
                    {{ parent_title }}
                    {% include "patterns/atoms/icons/icon.html" with name="chevron" classname="header__primary-menu-toggle-icon" %}
                </button>

            {# Primary mobile navigation #}
                <nav aria-label="Main navigation"  class="primary-nav-mobile" data-primary-mobile-menu>
                    {% wagtailcache 600 "primarynavmobile" current_site.pk is_pattern_library %}
                        <ul class="primary-nav-mobile__list">
                            <li class="primary-nav-mobile__item">
                                <a href="/" aria-label="Homepage link" class="primary-nav-mobile__link">
                                    <span class="primary-nav-mobile__text">Home</span>
                                </a>
                            </li>
                            {% primarynavmobile %}
                        </ul>
                    {% endwagtailcache %}
                </nav>

            {# Mode switcher desktop #}
                {% include "patterns/molecules/mode_switcher/mode_switcher.html" %}
            </div>
        </div>
    </div>
    <div class="grid">
        <div class="header__bottom grid__header-nav">
            <div class="header__logo">
                {% if page.final_division and page.final_division.logo %}
                    {% with class_name="logo logo--"|add:page.final_division.logo %}
                        {% include "patterns/atoms/icons/icon.html" with name=page.final_division.logo alt_text=page.final_division.get_logo_display classname=class_name %}
                    {% endwith %}
                {% else %}
                    {% include "patterns/atoms/icons/icon.html" with name="logo-torchbox" alt_text="Torchbox" classname="logo logo--logo-torchbox" %}
                {% endif %}
            </div>

            {# Secondary desktop navigation #}
            {% include "patterns/navigation/components/secondary-nav.html" %}

            {# Secondary mobile menu toggle #}
            {# Show the mobile menu toggle only if there is a navigation set assigned to the page #}
            {% if page.navigation_set %}
                <div class="header__secondary-menu-toggle">
                    <span class="sr-only">Menu</span>
                    <button class="button-menu-toggle" data-mobile-menu-toggle aria-haspopup="true" aria-expanded="false" aria-label="Mobile menu toggle">
                        <span class="button-menu-toggle__line"></span>
                        <span class="button-menu-toggle__line"></span>
                        <span class="button-menu-toggle__line"></span>
                        <span class="button-menu-toggle__line"></span>
                    </button>
                </div>
            {% endif %}

            {# Secondary mobile navigation #}
            {% include "patterns/navigation/components/secondary-nav-mobile.html" %}
        </div>
    </div>
</header>